---

compose_project_name: my-project
docker_runtime_dir: my-project
docker_cached_volume: true

host_machine_user: myusername

# Absolute Path to Drupal dir (`vendor` forlder should be there).
drupal_root_dir: /var/data/drupal
# Name of "web" folder inside `drupal_root_dir`.
drupal_web_root: web
# Absolute Path to Drupal files dir.
drupal_files_dir: /var/data/drupal_files
drupal_hash_salt: demo_site

apache_port: 80
apache_port_ssl: 443

# Look at available options here: https://github.com/jet-dev-team/docker-compose-lamp/tree/drupal/bin
phpversion: php74

# Enviroment variable for php xdebug extensions
xdebug_enviroment: remote_enable=1 remote_connect_back=1 remote_port=9008 remote_host=192.168.105.1 show_error_trace=0 show_local_vars=1 remote_autostart=1 show_exception_trace=0 idekey=VSCODE

# Setup additional networking.
advanced_networking: false
network_id: 105
domain_name: drupal.devel

init_project: false
composer_project: drupal/recommended-project
comoser_extras:
  - drush/drush
  - drupal/admin_toolbar

drush_install: true
# Availible options: 8, 9, 10
drush_version: 10

# Drush commands to run (will be run by `run-drush-commands.yml` playbook or if init_project is true).
drush_commands:
  - 'cc drush'
  - 'site:install minimal --account-pass=admin --site-name="Drupal Dockerizer"'
  - 'theme:enable bartik claro'
  - 'en datetime toolbar rest jsonapi views views_ui ban automated_cron action admin_toolbar'
  - 'config-set system.theme default bartik'
  - 'config-set system.theme admin claro'
  - 'cron'

solr: false
solr_core_name: drupal

# For woking in new prtoject add to your drush commands `en memcache`
memcache: false

# Path to Drupal DB dump (will be imported by `db.yml` playbook).
db_dump_path: /var/data/db/db.sql

database: mysql
mysql_root_password: root
mysql_user: docker
mysql_password: docker
mysql_database: docker

install_adminer: false
adminer_port: 8080

custom_drupal_settings: |
  if (file_exists($app_root . '/' . $site_path . '/settings.local.php')) {
    include $app_root . '/' . $site_path . '/settings.local.php';
  }
