---

- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - ../config.yml

  roles: []

  tasks:

    - name: Run Drush commands.
      include: tasks/drush-command.yml
      when: drush_install
