---

- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles: []

  tasks:

    - name: Include lamp setup tasks
      include: tasks/runtime-setup.yml

    - name: Include solr setup tasks.
      when: solr
      include: tasks/solr-setup.yml

    - name: Include Advanced Networking setup tasks
      when: advanced_networking
      include: tasks/advanced-networking-setup.yml

    - name: Include Settings setup tasks
      include: tasks/settings-setup.yml

    - name: Include Docker up tasks
      include: tasks/docker-up.yml

    - name: Include Memcache setup tasks
      when: memcache
      include: tasks/memcache-setup.yml
