---

- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles: []

  tasks:

    - name: Include lamp setup tasks
      include: tasks/runtime-setup.yml

    - name: Check project tasks.
      stat:
        path: "{{drupal_root_dir}}/.drupal_dockerizer/pre-tasks.yml"
      register: pre_tasks

    - name: Include custom project pre-tasks
      include: "{{ item }}"
      with_first_found:
        - files:
            - "{{drupal_root_dir}}/.drupal_dockerizer/pre-tasks.yml"
          skip: true
      when: pre_tasks

    - name: Include solr setup tasks.
      when: solr
      include: tasks/solr-setup.yml

    - name: Include Advanced Networking setup tasks
      when: advanced_networking
      include: tasks/advanced-networking-setup.yml

    - name: Include Settings setup tasks
      include: tasks/settings-setup.yml

    - name: Include Docker up tasks
      include: tasks/docker-up.yml

    - name: Include Memcache setup tasks
      when: memcache
      include: tasks/memcache-setup.yml

    - name: Wait docker containers (MySQL) to up.
      pause:
        seconds: 30

    - name: Check project tasks.
      stat:
        path: "{{drupal_root_dir}}/.drupal_dockerizer/post-tasks.yml"
      register: post_tasks

    - name: Include custom project post-tasks
      include: "{{ item }}"
      with_first_found:
        - files:
            - "{{drupal_root_dir}}/.drupal_dockerizer/post-tasks.yml"
          skip: true
      when: post_tasks
