---

- hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include config override file, if it exists.
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml

  roles: []

  tasks:

    - name: Stop all Docker containers.
      shell: |
        docker-compose stop
        chdir={{ docker_runtime_dir }}
