---

- name: Add memcache connection to settings.php
  become: true
  blockinfile:
    marker: "// {mark} {{ compose_project_name }} SETUP MEMCACHE BLOCK"
    path: "{{ drupal_root_dir }}/{{ drupal_web_root }}/sites/default/settings.php"
    block: |
      $settings['memcache']['servers'] = ['{{ compose_project_name }}-memcached:11211' => 'default'];
      $settings['memcache']['bins'] = ['default' => 'default'];
      $settings['cache']['default'] = 'cache.backend.memcache';
      $settings['cache']['bins']['render'] = 'cache.backend.memcache';
      $settings['memcache']['key_prefix'] = '{{ compose_project_name }}';
