---

- name: Install drupal project
  ignore_errors: yes
  become: no
  composer:
    command: create-project
    arguments: "{{composer_project}} {{ drupal_root_dir }}"
    working_dir: "/tmp"
    prefer_dist: yes

- name: Require extra packages.
  become: no
  loop: "{{ comoser_extras }}"
  composer:
      command: require
      arguments: "{{ item }} --no-update"
      working_dir: "{{ drupal_root_dir }}"

- name: Update project.
  become: no
  composer:
      command: update
      working_dir: "{{ drupal_root_dir }}"
      prefer_dist: yes

