---

- name: Make public files dir.
  file:
    path: '{{ drupal_files_dir }}'
    state: directory
    recurse: yes
    mode: '1777'
    owner: "{{ host_machine_user }}"

- name: Copy file with owner and permission, using symbolic representation
  copy:
    src: "{{ drupal_root_dir }}/{{ drupal_web_root }}/sites/default/default.settings.php"
    dest: "{{ drupal_root_dir }}/{{ drupal_web_root }}/sites/default/settings.php"
    mode: '444'
    owner: "{{ host_machine_user }}"

- name: Add DB connection to settings.php
  blockinfile:
    marker: "// {mark} {{ compose_project_name }} SETUP SETTINGS BLOCK"
    path: "{{ drupal_root_dir }}/{{ drupal_web_root }}/sites/default/settings.php"
    block: |
      $databases = [
        "default" => [
          "default" => [
            "database" => "{{ mysql_database}}",
            "username" => "{{ mysql_user }}",
            "password" => "{{ mysql_password }}",
            "host" => "{{ compose_project_name }}-database",
            "port" => "3306",
            "driver" => "mysql",
            "prefix" => "",
          ],
        ],
      ];
      $settings["file_temp_path"] = '/tmp';
      $settings['config_sync_directory'] = 'sites/default/sync';
      $settings['trusted_host_patterns'] = ['{{ domain_name }}'];
      {% if solr %}
      $config['search_api.server.solr']['backend_config']['connector_config']['host'] = '{{ compose_project_name }}-solr';
      {% endif %}
      $settings["hash_salt"] = '{{ drupal_hash_salt }}';
