---

- name: Clone docker solr4 repository.
  when: solr_version == 4
  git:
    repo: https://github.com/docker-solr/docker-solr4
    dest: "{{ docker_runtime_dir }}/bin/solr"
    version: master
    clone: yes
    update: yes
    force: yes

- name: Create solr directory
  when: solr_version != 4
  file:
    recurse: yes
    path: "{{ docker_runtime_dir }}/bin/solr"
    state: directory

- name: Create solr data directory
  when: solr_version != 4
  file:
    recurse: yes
    path: "{{ docker_runtime_dir }}/data/solr"
    state: directory

- name: Ensure Solr Dokcerfile is present.
  when: solr_version != 4
  template:
    src: templates/solr.Dockerfile.j2
    dest: "{{ docker_runtime_dir }}/bin/solr/Dockerfile"
    mode: '644'

- name: Ensure Solr Core file is present.
  template:
    src: templates/solr.core.j2
    dest: "{{ docker_runtime_dir }}/data/solr/core.properties"
    mode: '644'

- name: Copy drupal solr config.
  command: cp -r "{{ solr_configs_path }}"/. "{{ docker_runtime_dir }}/data/solr/conf"

